version = 1

[install]
gnumake.pkg-path = "gnumake"
python3.pkg-path = "python3"
curl.pkg-path = "curl"
gcc11.pkg-path = "gcc11"
# jq.pkg-path = "jq"

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]

[build]

# demo-project.buildCache = true
# demo-project.sandbox = true
demo-project.command = '''
  make
  make install PREFIX=$out
'''

# headlines.sandbox = false
# headlines-deps.command = '''
#   make install-headlines-dev PREFIX=$out
# '''

# headlines.sandbox = true
# headlines.command = '''
#   set -x # Remind ourselves which version we're using
#   make install-headlines PREFIX=$out
#   # make install-headlines-bin PREFIX=$out HEADLINESDIR=${headlines-deps}/include
#   # $out/bin/headlines # TEST
# '''

