version = 1

[install]
gcc.pkg-path = "gcc"
python3.pkg-path = "python3"
curl.pkg-path = "curl"
# jq.pkg-path = "jq"

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]

[build]

# demo-project.buildCache = true
# demo-project.sandbox = true
# demo-project.command = '''
#   make
#   make install PREFIX=$out
# '''

# headlines.sandbox = false
# headlines-deps.command = '''
#   make install-headlines-json PREFIX=$out
# '''

# headlines.sandbox = true
# headlines.command = '''
#   set -x # Remind ourselves which version we're using
#   mkdir -p $out
#   # make install-headlines PREFIX=$out
#   make install-headlines-bin PREFIX=$out HEADLINESDIR=${headlines-deps}/include
# '''

